"""updated the contributions model

Revision ID: 00bfc7b47aab
Revises: 11935ef26e38
Create Date: 2025-02-23 00:58:32.673947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00bfc7b47aab'
down_revision: Union[str, None] = '11935ef26e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contributions_campaign_id_key', 'contributions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contributions_campaign_id_key', 'contributions', ['campaign_id'])
    # ### end Alembic commands ###
