"""added a reputation score

Revision ID: 11430554c3f5
Revises: dafce646c420
Create Date: 2025-02-23 23:36:15.520439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11430554c3f5'
down_revision: Union[str, None] = 'dafce646c420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('reputation_score', sa.Float(), nullable=True))
    op.create_index(op.f('ix_contributions_contributor'), 'contributions', ['contributor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contributions_contributor'), table_name='contributions')
    op.drop_column('contributions', 'reputation_score')
    # ### end Alembic commands ###
