"""added the creator wallet address on the campaign model to ensure we know who created a campaign

Revision ID: 2492e4de9245
Revises: 11430554c3f5
Create Date: 2025-02-23 23:38:33.590870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2492e4de9245'
down_revision: Union[str, None] = '11430554c3f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('creator_wallet_address', sa.String(), nullable=True))
    op.create_index(op.f('ix_campaigns_creator_wallet_address'), 'campaigns', ['creator_wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_creator_wallet_address'), table_name='campaigns')
    op.drop_column('campaigns', 'creator_wallet_address')
    # ### end Alembic commands ###
