"""added the is premium field

Revision ID: 5e39eb3d225f
Revises: 2492e4de9245
Create Date: 2025-02-24 17:29:55.184591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e39eb3d225f'
down_revision: Union[str, None] = '2492e4de9245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_campaigns_is_premium'), 'campaigns', ['is_premium'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_is_premium'), table_name='campaigns')
    op.drop_column('campaigns', 'is_premium')
    # ### end Alembic commands ###
