"""added current activity level for campaigns

Revision ID: 9c904ea441e4
Revises: fca33b53ad8e
Create Date: 2025-02-26 13:01:12.786557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c904ea441e4'
down_revision: Union[str, None] = 'fca33b53ad8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('current_activity_level', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'current_activity_level')
    # ### end Alembic commands ###
