"""added relationship between analytics and contribution

Revision ID: c9a8b8123913
Revises: 9c904ea441e4
Create Date: 2025-02-26 19:21:07.971743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a8b8123913'
down_revision: Union[str, None] = '9c904ea441e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('contribution_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'activity', 'contributions', ['contribution_id'], ['contribution_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_column('activity', 'contribution_id')
    # ### end Alembic commands ###
