"""added the ai verification score to contributions

Revision ID: dafce646c420
Revises: 00bfc7b47aab
Create Date: 2025-02-23 20:35:43.827401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dafce646c420'
down_revision: Union[str, None] = '00bfc7b47aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('ai_verification_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributions', 'ai_verification_score')
    # ### end Alembic commands ###
