"""removed data hash and signature from contributions model

Revision ID: f55f1d1d08b1
Revises: 5e39eb3d225f
Create Date: 2025-02-25 15:31:11.091100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55f1d1d08b1'
down_revision: Union[str, None] = '5e39eb3d225f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributions', 'signature')
    op.drop_column('contributions', 'data_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('data_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contributions', sa.Column('signature', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
