"""added the campaign type to the campaign model

Revision ID: fe269c6a3c1d
Revises: 51bd398bfcc0
Create Date: 2025-02-22 23:08:48.926523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe269c6a3c1d'
down_revision: Union[str, None] = '51bd398bfcc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('campaign_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_campaigns_campaign_type'), 'campaigns', ['campaign_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_campaign_type'), table_name='campaigns')
    op.drop_column('campaigns', 'campaign_type')
    # ### end Alembic commands ###
